# Generated by Django 4.2.5 on 2023-09-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goods_delete_good'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Item',
        ),
    ]
